version: "3"
services:
  db:
    image: postgres:14.2
    container_name: postgres
    ports:
      - "5432:5432"
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: concurrency
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: no
    volumes:
      - ./data/redis:/data

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: no

